

POST https://itm-301-biydaalt-4.onrender.com/api/user/questions/add
Content-Type: application/json
Accept: application/json

{
    "name": "Uuganaa",
    "email": "uugnaauugaa@gmail.com",
    "school_name" : "MUST",
    "picture" : "Image_url",
    "message": "hello"
}

###
GET https://itm-301-biydaalt-4.onrender.com/api/admin/questions/get
Content-Type: application/json
Accept: application/json


###
GET https://itm-301-biydaalt-4.onrender.com/api/messages/chats?userId=568
Content-Type: application/json
Accept: application/js

###
PUT https://itm-301-biydaalt-4.onrender.com/api/admin/questions/edit/692d185eaedacccf3f35f2a2
Content-Type: application/json
Accept: application/json

{
    "name": "Uuganaa",
    "email": "uugnaauugaa@gmail.com",
    "message": "hello edited message"
}


###
DELETE https://itm-301-biydaalt-4.onrender.com/api/admin/questions/delete/692d1a706c689741027fe0ab
Content-Type: application/json
Accept: application/json


