
POST http://localhost:5001/api/notifications/send
Authorization: Bearer KICySuO4v7O90wXo0mF4WA
Content-Type: application/json

{
  "title": "Buh hereglegch",
  "message": "Hello students",
  "type": "general",
  "targetType": "all"
}


### 2. Send Notification to role (example: student)
POST http://localhost:5001/api/notifications/send
Content-Type: application/json
Authorization: Bearer _qltbxg3VJssRZA69Of_eQ

{
  "title": "New Homework",
  "message": "Маргааш 101-р хичээлд даалгавар шалгана.",
  "type": "warning",
  "targetType": "role",
  "targetValue": "student"
}

### 3. Send Notification to course students
POST http://localhost:5001/api/notifications/send
Content-Type: application/json
Authorization: Bearer NE2H5yJk_EnZYpQml5mtMQ

{
  "title": "Exam Notice",
  "message": "Web system хичээлийн шалгалт тун удахгүй.",
  "type": "alert",
  "targetType": "course",
  "targetValue": "200"
}

### 4. Send Notification to single user
POST http://localhost:5001/api/notifications/send
Content-Type: application/json
Authorization: Bearer qdSBj5edoPkuuPnqsOulEQ

{

  "title": "Web system: 30 оноо",
  "message": "30 онооны шалгалтыг 17р долоо хоногт танхимаар авна.",
  "targetType": "user",
  "targetValue": "568"
}

### 5. Get my notifications
GET http://localhost:5001/api/notifications/my
Authorization: Bearer _qltbxg3VJssRZA69Of_eQ

###
GET https://todu.mn/bs/lms/v1/courses/200/users?limit=1000
Content-Type: application/json
Authorization: Bearer luwIpM9Fg86ZH7o8nANBIw



### 5. Get my notification
GET http://localhost:5001/api/notifications/6936673a59789899458c28b2
Authorization: Bearer K0AvHqNDbVLD9W9oXBm-mw

### 6. Mark notification as read
PUT http://localhost:5001/api/notifications/read/67a1b82f879a93f7cc21b93b
Authorization: Bearer {{token}}


###
POST https://todu.mn/bs/lms/v1/token/email
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "email": "teacher@must.edu.mn",
  "password": 123
}




###
GET https://todu.mn/bs/lms/v1/users?limit=2
Content-Type: application/json
Authorization: Bearer _qltbxg3VJssRZA69Of_eQ
